name: Printing Node Versions

on:
  push:
   branches: 
    - main


jobs:
 versions:
  runs-on: ubuntu-latest 
  steps: 
   - name: checkout
     uses: actions/checkout@v3
   - name: install node 
     uses: actions/setup-node@v2
     with:
         node-version: "16.x"   
   - name: Print Node Version
     run: node -v         
